# Generated by Django 4.2.3 on 2023-08-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pichangasApp', '0002_equipo_app_pichanga_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pichanga_app',
            name='equipo_local',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AlterField(
            model_name='pichanga_app',
            name='equipo_visita',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AlterField(
            model_name='pichanga_app',
            name='estadoPichanga',
            field=models.CharField(default='Programada', max_length=128),
        ),
        migrations.AlterField(
            model_name='pichanga_app',
            name='marcador_local',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AlterField(
            model_name='pichanga_app',
            name='marcador_visita',
            field=models.CharField(default='0', max_length=128),
        ),
    ]
